#! /bin/sh
#COMPDIR=/proj/hci/src/langs/1/bcpl/local/boot
COMPDIR=.
if test $# -lt 1
then
	1>&2 echo "Usage: $0 file"
	exit 1
fi
if test ! -r $1
then
	1>&2 echo "$0: $1: no such file"
	exit 1
fi
if $COMPDIR/icint $COMPDIR/s.int < $1
then
	if $COMPDIR/icint $COMPDIR/c.int < OCODE
	then
		intfile=`basename $1 .bpl`.int
		echo "$COMPDIR/icint" '$0; exit $?' > $intfile
		cat $COMPDIR/iclib.int $COMPDIR/blib.int INTCODE >> $intfile
		chmod 755 $intfile
	fi
fi
